# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Integration Tests

on:
  pull_request:
    branches:
      - main
      - develop
    push:
      branches:
        - main
        - develop
      tags:
        - '*' # Push events to every tag

jobs:
  integration_tests:
    name: name: ${{ matrix.destination }} Integration Tests
    strategy:
      matrix:
        os: [macos-15]
        destination: ["platform=macOS", "name=iPhone 16", "name=iPad Pro 13-inch (M4)", "name=Apple Watch SE (44mm) (2nd generation)", "name=Apple Tv 4K (3rd Generation)", "name=Apple Vision Pro"]
		destinationName: ["macOS", "iOS", "iPadOS", "AppleWatch", "AppleTv", "AppleVisionPro"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ matrix.os }}-spm-${{ matrix.destinationName }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ matrix.os }}-spm-${{ matrix.destinationName }}-

      - name: Build
        run: xcodebuild build-for-testing -scheme OSLogClientIntegrationTests -destination "${{ matrix.destination }}"

      - name: Test
        run: xcodebuild test -scheme OSLogClientIntegrationTests -destination "${{ matrix.destination }}" -enableCodeCoverage YES